# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  min_messages: warning
  username: postgres
  password: postgres
  host: localhost
  port: 5433

development:
  <<: *default
  database: multitenancy_rails_development
test:
  <<: *default
  database: multitenancy_rails_test

production:
  <<: *default
  database: multitenancy_rails_production
